name: "Package and Delivery"

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    name: "Package and Delivery"
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - name: "Git Checkout"
        uses: actions/checkout@v4.2.2

      - name: "Set up JDK 21"
        if: success()
        uses: actions/setup-java@v4.7.0
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: "Increment version"
        id: increment-version
        uses: RichardInnocent/semantic-versioning-maven@v0.1.0

      - name: Update version in changelog
        run: |
          sed -i 's/## \[Unreleased\]/## \[Unreleased\]\n\n## [v'"${TAG_VERSION}"'] - '"$(date +'%Y-%m-%d')"'/g' CHANGELOG.md
        env:
          TAG_VERSION: ${{ steps.increment-version.outputs.new-version }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: Bump version to ${{ steps.increment-version.outputs.new-version }}"
          git push

      - name: "Package with Maven"
        if: success()
        run: mvn -U -B package --file pom.xml

      - name: "Docker Setup Buildx"
        if: success()
        uses: docker/setup-buildx-action@v3.10.0
        with:
          platforms: ${{ vars.DOCKER_PLATFORMS }}

      - name: "Docker Login"
        if: success()
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Docker Build and Push"
        if: success()
        uses: docker/build-push-action@v6.15.0
        with:
          push: true
          context: .
          file: Dockerfile
          platforms: ${{ vars.DOCKER_PLATFORMS }}
          tags: '${{ vars.DOCKERHUB_TAG }}:${{ steps.increment-version.outputs.new-version }}'
